events/urls.py
from django.urls import re_path
from django.views.generic.detail import DetailView

from .models import Event
from .views import (EventDetail,
                    EventList,
                    EventCreate,
                    EventUpdate,
                    EventDelete,
                    EventsFeed,
                    EventParticipationList,
                    EventParticipationCreate,
                    EventParticipationDetail,
                    EventParticipationDelete,
                    EventParticipationDownload)

urlpatterns = [
    re_path(r'^$', EventList.as_view(), name='events_list_all'),
    re_path(r'^rss$', EventsFeed(), name='events_feed'),
    re_path(r'^(?P<pk>\d+)/$', EventDetail.as_view(), name='detail'),
    re_path(r'^add/$', EventCreate.as_view(), name='add'),
    re_path(r'^(?P<pk>\d+)/editar/$', EventUpdate.as_view(), name='edit'),
    re_path(r'^(?P<pk>\d+)/borrar/$', EventDelete.as_view(), name='delete'),
    re_path(r'^(?P<slug>[\w-]+)/$', DetailView.as_view(model=Event), name='event_slug'),

    # Event Registration Management
    re_path(r'^(?P<pk>\d+)/inscribirse/$', EventParticipationCreate.as_view(), name='register'),
    re_path(r'^(?P<pk>\d+)/inscriptos/$', EventParticipationList.as_view(), name='registered'),
    re_path(r'^(?P<pk>\d+)/inscriptos/csv/$', EventParticipationDownload.as_view(),
            name='registered_csv'),
    re_path(r'^(?P<pk>\d+)/inscripcion/(?P<participation_pk>\d+)/$',
            EventParticipationDetail.as_view(),
            name='registration'),
    re_path(r'^(?P<pk>\d+)/inscripcion/(?P<participation_pk>\d+)/borrar/$',
            EventParticipationDelete.as_view(), name='unregister'),
]

joboffers/urls.py
from django.urls import re_path
from .views import (
    DownloadAnalyticsAsCsv, JobOfferAdminView, JobOfferAnalyticsView, JobOfferApproveView,
    JobOfferCreateView, JobOfferDeactivateView, JobOfferDetailView, JobOfferHistoryView,
    JobOfferListView, JobOfferUpdateView, JobOfferRejectView, JobOfferReactivateView,
    JobOfferRequestModerationView, TrackContactInfoView, JobOffersFeed
)


urlpatterns = [
    re_path(r'^$', JobOfferListView.as_view(), name='list'),
    re_path(r'^admin/$', JobOfferAdminView.as_view(), name='admin'),
    re_path(r'^nueva/$', JobOfferCreateView.as_view(), name='add'),
    re_path(r'^rss/$', JobOffersFeed(), name='feed'),
    re_path(r'^(?P<slug>[\w-]+)/rechazar/$', JobOfferRejectView.as_view(), name='reject'),
    re_path(r'^(?P<slug>[\w-]+)/aceptar/$', JobOfferApproveView.as_view(), name='approve'),
    re_path(
        r'^(?P<slug>[\w-]+)/desactivar/$', JobOfferDeactivateView.as_view(),
        name='deactivate'
    ),
    re_path(
        r'^(?P<slug>[\w-]+)/reactivar/$', JobOfferReactivateView.as_view(),
        name='reactivate'
    ),
    re_path(
        r'^(?P<slug>[\w-]+)/solicitar-moderacion/$', JobOfferRequestModerationView.as_view(),
        name='request_moderation'
    ),
    re_path(
        r'^(?P<slug>[\w-]+)/historial/$', JobOfferHistoryView.as_view(),
        name='history'
    ),
    re_path(r'^(?P<slug>[\w-]+)/$', JobOfferDetailView.as_view(), name='view'),
    re_path(
        r'^(?P<slug>[\w-]+)/editar$', JobOfferUpdateView.as_view(),
        name='edit'
    ),
    re_path(
        r'^(?P<slug>[\w-]+)/track-contact-info-view$', TrackContactInfoView.as_view(),
        name='track-contact-info-view'
    ),
    re_path(
        r'^(?P<slug>[\w-]+)/analitica$', JobOfferAnalyticsView.as_view(),
        name='analytics'
    ),
    re_path(
        r'^(?P<slug>[\w-]+)/visitas.csv$', DownloadAnalyticsAsCsv.as_view(),
        name='download-analytics-csv'
    )
]

jobs/urls.py
from django.contrib.auth.decorators import login_required
from django.views.generic.detail import DetailView
from django.urls import re_path
from .models import Job
from .views import (JobCreate, JobList, JobDelete, JobUpdate, JobsFeed,
                    JobInactivate)


urlpatterns = [
    re_path(r'^$', JobList.as_view(), name='jobs_list_all'),
    re_path(r'^rss$', JobsFeed(), name='jobs_feed'),
    re_path(r'^add/$', login_required(JobCreate.as_view()), name='jobs_add'),
    re_path(r'^(?P<slug>[\w-]+)/$', DetailView.as_view(model=Job), name='jobs_view'),
    re_path(r'^(?P<pk>\d+)/delete/$', login_required(JobDelete.as_view()), name='jobs_delete'),
    re_path(r'^(?P<pk>\d+)/update/$', login_required(JobUpdate.as_view()), name='jobs_update'),
    re_path(r'^(?P<pk>\d+)/inactivate/$', login_required(JobInactivate.as_view()),
            name='jobs_inactivate'),
]

pyarweb/urls.py
# -*- coding: utf-8 -*-


"""URLS configurations for PyAr Web."""
import re

from django.conf import settings
from django.conf.urls import include
from django.contrib import admin
from django.urls import re_path
from django.views.static import serve

from .views import buscador, irc

from community.views import homepage

admin.autodiscover()

app_name = 'pyarweb'
urlpatterns = [
    re_path(r'^irc/$', irc, name='irc'),
    re_path(r'^buscador/$', buscador, name='buscador'),

    re_path(r'^$', homepage, name='homepage'),

    re_path(r'^noticias/', include('news.urls')),
    re_path(r'^empresas/', include(('pycompanies.urls', 'pycompanies'), namespace='companies')),
    re_path(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
    re_path(r'^summernote/', include('django_summernote.urls')),
    re_path(r'^trabajo-vieja/', include('jobs.urls')),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^accounts/', include('allauth.urls')),
    re_path(r'^eventos/', include(('events.urls', 'events'), namespace='events')),
    re_path(r'^captcha/', include('captcha.urls')),
    re_path(r'^trabajo/', include(('joboffers.urls', 'joboffers'), namespace='joboffers')),

    # no puedo usar el static porque no funcia en produccion y en prod django esta
    # sirviendo los archivos estaticos. Esto es sacado del codigo de la funcion.
    # si es un HACK, pero hasta que pueda solucionarlo usando django-assets o algo asi
    re_path(
        r'^%s(?P<path>.*)$' % re.escape(settings.STATIC_URL.lstrip('/')),
        serve,
        kwargs=dict(document_root=settings.STATIC_ROOT)
    ),
    re_path(
        r'^%s(?P<path>.*)$' % re.escape(settings.MEDIA_URL.lstrip('/')),
        serve,
        kwargs=dict(document_root=settings.MEDIA_ROOT)
    ),
]

pycompanies/urls.py
from django.urls import re_path

from .views import (
  CompanyAdminView,
  CompanyAnalyticsView,
  CompanyAssociateView,
  CompanyAssociationListView,
  CompanyCreateView,
  CompanyDeleteView,
  CompanyDetailView,
  CompanyDisassociateView,
  CompanyListView,
  CompanyUpdateView
)

app_name = 'pycompanies'
urlpatterns = [
    re_path(r'^$', CompanyListView.as_view(), name='company_list_all'),
    re_path(r'^(?P<pk>\d+)/$', CompanyDetailView.as_view(), name='detail'),
    re_path(r'^agregar/$', CompanyCreateView.as_view(), name='add'),
    re_path(r'^(?P<pk>\d+)/editar/$', CompanyUpdateView.as_view(), name='edit'),
    re_path(r'^(?P<pk>\d+)/eliminar/$', CompanyDeleteView.as_view(), name='delete'),
    re_path(r'^(?P<company>\d+)/asociar/$', CompanyAssociateView.as_view(), name='associate'),
    re_path(r'^asociarme/$', CompanyAssociationListView.as_view(), name='association_list'),
    re_path(r'^admin/$', CompanyAdminView.as_view(), name='admin'),
    re_path(r'^(?P<pk>\d+)/desasociar/$', CompanyDisassociateView.as_view(), name='disassociate'),
    re_path(r'^(?P<pk>\d+)/analitica/$', CompanyAnalyticsView.as_view(), name='analytics')
]

templates/companies/_user_actions.html
{% load i18n %}
<div class="list-group my-actions">
  {% if own_company %}
    <div class="list-group-item">
      <div class="h4 list-group-item-heading flex-center">
        <span>{{ own_company.name }}</span>
        <span class="pull-right">
          <i class="fa fa-building" style="font-size: 1.5em;"></i>
        </span>
      </div>
    </div>

    <div class="list-group-item">
      <a href="{% url 'joboffers:admin' %}" class="btn btn-default">
        {% trans 'Administrar Ofertas' %}
      </a>
      <a href="{% url 'companies:analytics' own_company.id %}" class="btn btn-dark-green">
        {% trans 'Analítica de Ofertas' %}
      </a>
    </div>
  {% else %}
    <div class="list-group-item">
      <div class="h4 list-group-item-heading flex-center">
        <span>{{ user.username }}</span>
        <span class="pull-right">
          <i class="fa fa-user" style="font-size: 1.5em;"></i>
        </span>
      </div>
    </div>
    <div class="list-group-item">
      <a href="{% url 'companies:admin' %}" class="btn btn-default btn-md">
        {% trans 'Asociarme a Empresa' %}
      </a>
    </div>
  {% endif %}
</div>

templates/companies/companies_by_user.html
{% extends "base.html" %}

{% load devtags %}

{% block content %}
<main id="main" class="container" role="main">
    <div class="row">
        <div class="col-md-7">
            <!-- Últimas noticias -->

            <section class="list-group">
                <header class="list-group-item">
                    <h3 class="list-group-item-heading">Companias que usan Python</h3>
                    </header>
                  {% if companies|length < 1 %}
                      <article class="list-group-item">
                        <h4 class="list-group-item-heading">You dont have company to edit</h4>
                        <a href='/companies/add'>Add your company</a>
                      </article>
                  {% else %}
                  {% for company in companies %} 
                    <article class="list-group-item">
                      <h4 class="list-group-item-heading">{{ company.link }}</h4>
                      <a href='/companies/{{company.id}}/edit'>{{company.link}}</a>
                      </article>
                      {% endfor %}
                    {% endif %}
            </section>
        </div>
        <div class="col-md-5">
        
            <!-- SeachBox -->

            <form id="search-form" class="input-group" role="form">
                <input type="text" class="form-control input-lg" placeholder="Buscar...">
                <span class="input-group-btn">
                    <button class="btn btn-default btn-lg" type="button">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </span>
            </form>

            <!-- Próximos eventos -->

            <section class="list-group">
                <header class="list-group-item">
                    <h3 class="list-group-item-heading">Próximos eventos</h3>
                </header>
                {% for i in 4|get_range %} 
                    <article class="list-group-item">
                        <h4 class="list-group-item-heading">PyCon Argentina</h4>
                        <p class="list-group-item-text"><span>23 de Agosto de 2012</span> | <span>20:00 hs</span> | <span>Audotorio UnQui</span></p>
                    </article>
                {% endfor %}
            </section>

            <!-- Planeta PyAr -->

            <section class="list-group">
                <header class="list-group-item">
                    <h3 class="list-group-item-heading">Planeta PyAr</h3>
                </header>
                {% for i in 4|get_range %} 
                    <article class="list-group-item">
                        <h4 class="list-group-item-heading">Mi experiencia con PyQT y HTML5</h4>
                        <p class="list-group-item-text"><span class="text-muted">via: </span><span>http://elblogdefulanito...</span><span class="text-muted"> | 23-05-2012 | 22:05</span></p>
                    </article>
                {% endfor %}
            </section>
        </div>
    </div>
</main>
{% endblock %}

templates/companies/company_admin.html
{% extends "base_site.html" %}
{% load devtags %}
{% load i18n static pagination_tags devtags %}
{% block title %}Administrar Empresa{% endblock %}
{% block left-column %}
  <!-- Administrar Empresa -->
  <section>
    <div class="page-header">
      <h2>
        {{own_company}}
      </h2>
    </div>
    <div>

        <section class="list-group col-md-8">
          <header class="list-group-item">
              <h3 style="margin:0;">
                {% trans 'Usuaries vinculades'%}
              </h3>
          </header>
          <article class="list-group-item">
            {% if company_users %}
              {% for company_user in company_users %}
                  <h4>
                  {{company_user.user.username}}
                  <a href="{% url 'companies:disassociate' company_user.id%}" class="btn btn-danger btn-xs ">
                    {% if user == company_user.user %}
                      {% trans 'Desvincularme' %}
                    {% else %}
                      {% trans 'Desvincular' %}
                    {% endif %}
                  </a>
                </h4>
              {% endfor %}
          {% else %}
              <div class="col-md-12">
                  <p>{% trans 'No hay usuaries vinculades.' %}</p>
              </div>
          {% endif %}
          </article>
        </section>
      <div class="col-md-4">
        <h3>{% trans 'Vincular usuarie'%}</h3>
        <form method="POST" action="{% url 'companies:associate' own_company.id %}"  class="input-group">
          {% csrf_token %}
          <input type="search" name="username" class="form-control input-md" placeholder="Usuarie..." value="" required="">
          <span class="input-group-btn">
            <button class="btn btn-success btn-md" type="submit">
                Vincular
            </button>
          </span>
        </form>
      </div>
    </div>
  </section>
{% endblock %}

templates/companies/company_analytics.html
{% extends "base.html" %}
{% load i18n %}
{% load email_obfuscator %}
{% load devtags %}

{% block title %}
{{ object.title }}
{% endblock %}

{% block content %}
<main id="main" class="joboffers container" role="main">
  <div class="col-lg-12">
    <div class="page-header">
      <h2>{% trans 'Estadísticas de ' %} {{ company.name }}</h2>
    </div>
    <div class="row">
      <div class="col-xs-12">
        {% for title, graph in graphs %}
        <h2>{{ title }} {% trans '(todas las  ofertas)' %}</h2>
          {% if graph %}
            {% autoescape off %}
              {{ graph }}
            {% endautoescape %}
          {% else %}
             {% trans 'No información de las visitas para mostrar.' %}
          {% endif %}
        {% endfor %}

        <h2>{% trans 'Resumen de Visualizaciones' %}</h2>

        <table class="table table-bordered">
          <tr>
            <th>{% trans 'Fecha de Creación' %}</th>
            <th>{% trans 'Oferta' %}</th>
            <th>{% trans 'Tags' %}</th>
            <th>{% trans 'Vis. en Listado' %}</th>
            <th>{% trans 'Vis. de Detalle (Individual)' %}</th>
            <th>{% trans 'Vis. de Datos de Contacto' %}</th>
          </tr>
          {% for offer, listing_views, detail_views, contact_info_views in joboffers_data %}
              <tr>
                <td>{{ offer.created_at | date:"SHORT_DATE_FORMAT" }}</td>
                <td><a href="{% url 'joboffers:analytics' offer.slug %}">{{ offer.title }}</a></td>
                <td>
                  {% for tag in offer.tags.all %}
                  <span clss="label label-default">{{ tags }}</span>
                  {% empty %}
                  -
                  {% endfor %}
                </td>
                <td>{{ listing_views }}</td>
                <td>{{ detail_views }}</td>
                <td>{{ contact_info_views }}</td>
              </tr>
              {% empty %}
              <td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td>
              {% endfor %}
        </table>

      </div>
    </div>
  </div>
</main>
{% endblock %}

templates/companies/company_association_list.html
{% extends "base_site.html" %}
{% load devtags %}
{% load i18n static pagination_tags devtags %}
{% block title %}Administrar Empresa{% endblock %}
{% block left-column %}
  <!-- Administrar Empresa -->
    <section>
      <h3>
        {% trans 'Busca la empresa a la que querés asociarte' %}
      </h3>
      <form type="GET" class="input-group">
        <input type="search" name="empresa" class="form-control input-lg" placeholder="Nombre de la empresa..." value="{{busqueda}}">
        <span class="input-group-btn">
          <button class="btn btn-default btn-lg" type="submit">
              <span class="glyphicon glyphicon-search"></span>
          </button>
        </span>
      </form>
      <div>
      {% if companies_and_owners %}
      <div class="accordion" id="companiesAccordion">
        {% for company, owner_names in companies_and_owners %}
          <div>
            <a data-toggle="collapse" href="#collapse-{{company.id}}" role="button" aria-expanded="false" aria-controls="collapse-{{company.id}}">
              <h3 style="color: #666;" >{{company.name}}</h3>
            </a>
            <div class="collapse" id="collapse-{{company.id}}" data-parent="#companiesAccordion">
            {% if company.users.all %}
              <h4>Para asociarte a la empresa, por favor comunicate con alguna de estas personas:</h4>
            {% endif %}
            {% for owner_name in owner_names %}
              <h4 style="color:#428bca;">
                {{ owner_name }}
              </h4>
            {% empty %}
              <h4>{% trans 'No hay ninguna persona asociada a esta empresa.' %}</h4>
              <h4>{% trans 'Por favor, enviá un email a admin@python.org.ar para solicitar que te asocien.' %}</h4>
            {% endfor %}
            </div>
          </div>
        {% endfor %}
        </div>
      {% elif busqueda  %}
        <div class="col-md-12">
            <p>{% trans 'No existen empresas para esta busqueda. Podés <a href="/empresas/agregar/">crear una empresa acá</a>.' %}</p>
        </div>
      {% endif %}
    </div>
  </section>
{% endblock %}

{% block right-column %}
{% endblock %}

templates/companies/company_confirm_delete.html
{% extends "base.html" %}

{% load i18n %}

{% load devtags %}

{% block content %}

    <main id="main" class="container" role="main">
        <div class="row">
            <div class="col-md-12">
                <form method="post">{% csrf_token %}
                    {% trans "Are you sure you want to delete" %} "{{ object.name }}" ?
                    <input type="submit" value="Yes" class="btn btn-danger">
                    <a href="{% url 'companies:company_list_all' %}" class="btn btn-default">No</a>
                </form>
            </div>
        </div>
    </main>

{% endblock %}

templates/companies/company_confirm_disassociate.html
{% extends "base.html" %}

{% load i18n %}

{% load devtags %}

{% block content %}

    <main id="main" class="container" role="main">
        <div class="row">
            <div class="col-md-12">
                <form method="post">{% csrf_token %}
                    <h3>{{message}}</h3>
                    <input type="submit" value="Si" class="btn btn-danger">
                    <a href="{% url 'companies:admin' %}" class="btn btn-default">No</a>
                </form>
            </div>
        </div>
    </main>

{% endblock %}

templates/companies/company_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load devtags %}
{% block title %}
  {{ object.title }}
{% endblock title %}

{% block content %}
<main id="main" class="container" role="main">
    <div class="col-lg-12">
      <div class="page-header">
        <h2>
          {{ object.name }}
          <span class="pull-right">
            {% if user_company_related or user_is_superuser %}
              <a href="{% url 'companies:analytics' object.id %}" class="btn btn-dark-green">{% trans 'Ver analítica' %}</a>
              <a href="{% url 'companies:edit' object.id %}" class="btn btn-info">{% trans 'Editar datos' %}</a>
            {% endif %}
            {% if user_company_related %}
              <a href="{% url 'companies:disassociate' object.id %}" class="btn btn-danger">{% trans 'Desvincularme' %}</a>
            {% endif %}
          </span>
        </h2>
      </div>
      <div class="row">
        <div class="col-md-8">
          <article>
            <p>{% autoescape off %}{{ object.description|linebreaks|safe }}{% endautoescape %}</p>
          </article>
        </div>
        <div class="col-md-4">
          <a href="{{ object.link }}" target="blank">
            <img style="max-width:200px; height:auto;" src="{{ object.photo.url }}"></img>
          </a>
        </div>
      </div>
      {% if object.rank > 0%}
        <hr/>
        <p> Socia Benefactora de la <a href="https:/ac.python.org.ar/">Asociación Civil Python Argentina</a></p>
        <img src="https://ac.python.org.ar/images/acpyar.png" class="img-thumbnail" style="max-width:300px; height:auto;"/>
      {% endif %}
  </div>
</main>
{% endblock %}

templates/companies/company_form.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% load devtags %}

{% block stylesheets %}
  <link rel="stylesheet" href="/static/css/event_map.css">
{% endblock %}

{% block content %}
	<main id="main" class="container" role="main">
	    <div class="col-lg-12">
		    <div class="page-header">
		    	<h2>{% if form.instance.id %}
		    			{% trans 'Editar Empresa' %}
		    		{% else %}
		    			{% trans 'Agregar Empresa' %}
		    		{% endif %}
		    	</h2>
		    </div>
		    {% crispy form %}
		</div>
	</main>
{% endblock %}

templates/companies/company_list.html
{% extends "base_site.html" %}
{% load devtags %}
{% load i18n static pagination_tags devtags %}
{% block title %}Empresas que utilizan Python{% endblock %}
{% block left-column %}
  <!-- Empresas que utilizan python -->
  <section>
    <section class="list-group" style="margin-bottom: 0px;">
    </section>
      <div class="col-md-12">
          <div class="page-header">
              <h2>{% trans 'Empresas que utilizan Python' %}
                <span class="section-button-group">
                  {% if not own_company %}
                  <a href="{% url 'companies:add' %}" class="btn btn-info">{% trans 'Agregar Empresa' %}</a>
                  {% endif %}
                </span>
              </h2>
          </div>
          {% if object_list %}
              {% for object in object_list %}
                <h3>
                    <a href="{{ object.get_absolute_url }}">{{ object.name }}</a>
                </h3>
                <p>{{ object.description|striptags|truncatewords:"20" }}</p>
                <p><a href="{{ object.get_absolute_url }}">{% trans 'Más información...' %}</a></p>
              {% endfor %}

              {% paginate %}
          {% else %}
              <div class="col-md-12">
                  <p>{% trans 'La búsqueda no produjo resultados.' %}</p>
              </div>
          {% endif %}
      </div>
  </section>
{% endblock %}

{% block right-column %}
  {% if user.is_authenticated %}
    {% include "companies/_user_actions.html" %}
  {% endif %}

  {{ block.super }}

  {% include "_tags_filtering_form.html" %}
{% endblock %}