joboffers/urls.py
from django.urls import re_path
from .views import (
    DownloadAnalyticsAsCsv, JobOfferAdminView, JobOfferAnalyticsView, JobOfferApproveView,
    JobOfferCreateView, JobOfferDeactivateView, JobOfferDetailView, JobOfferHistoryView,
    JobOfferListView, JobOfferUpdateView, JobOfferRejectView, JobOfferReactivateView,
    JobOfferRequestModerationView, TrackContactInfoView, JobOffersFeed
)


urlpatterns = [
    re_path(r'^$', JobOfferListView.as_view(), name='list'),
    re_path(r'^admin/$', JobOfferAdminView.as_view(), name='admin'),
    re_path(r'^nueva/$', JobOfferCreateView.as_view(), name='add'),
    re_path(r'^rss/$', JobOffersFeed(), name='feed'),
    re_path(r'^(?P<slug>[\w-]+)/rechazar/$', JobOfferRejectView.as_view(), name='reject'),
    re_path(r'^(?P<slug>[\w-]+)/aceptar/$', JobOfferApproveView.as_view(), name='approve'),
    re_path(
        r'^(?P<slug>[\w-]+)/desactivar/$', JobOfferDeactivateView.as_view(),
        name='deactivate'
    ),
    re_path(
        r'^(?P<slug>[\w-]+)/reactivar/$', JobOfferReactivateView.as_view(),
        name='reactivate'
    ),
    re_path(
        r'^(?P<slug>[\w-]+)/solicitar-moderacion/$', JobOfferRequestModerationView.as_view(),
        name='request_moderation'
    ),
    re_path(
        r'^(?P<slug>[\w-]+)/historial/$', JobOfferHistoryView.as_view(),
        name='history'
    ),
    re_path(r'^(?P<slug>[\w-]+)/$', JobOfferDetailView.as_view(), name='view'),
    re_path(
        r'^(?P<slug>[\w-]+)/editar$', JobOfferUpdateView.as_view(),
        name='edit'
    ),
    re_path(
        r'^(?P<slug>[\w-]+)/track-contact-info-view$', TrackContactInfoView.as_view(),
        name='track-contact-info-view'
    ),
    re_path(
        r'^(?P<slug>[\w-]+)/analitica$', JobOfferAnalyticsView.as_view(),
        name='analytics'
    ),
    re_path(
        r'^(?P<slug>[\w-]+)/visitas.csv$', DownloadAnalyticsAsCsv.as_view(),
        name='download-analytics-csv'
    )
]

jobs/urls.py
from django.contrib.auth.decorators import login_required
from django.views.generic.detail import DetailView
from django.urls import re_path
from .models import Job
from .views import (JobCreate, JobList, JobDelete, JobUpdate, JobsFeed,
                    JobInactivate)


urlpatterns = [
    re_path(r'^$', JobList.as_view(), name='jobs_list_all'),
    re_path(r'^rss$', JobsFeed(), name='jobs_feed'),
    re_path(r'^add/$', login_required(JobCreate.as_view()), name='jobs_add'),
    re_path(r'^(?P<slug>[\w-]+)/$', DetailView.as_view(model=Job), name='jobs_view'),
    re_path(r'^(?P<pk>\d+)/delete/$', login_required(JobDelete.as_view()), name='jobs_delete'),
    re_path(r'^(?P<pk>\d+)/update/$', login_required(JobUpdate.as_view()), name='jobs_update'),
    re_path(r'^(?P<pk>\d+)/inactivate/$', login_required(JobInactivate.as_view()),
            name='jobs_inactivate'),
]

pyarweb/urls.py
# -*- coding: utf-8 -*-


"""URLS configurations for PyAr Web."""
import re

from django.conf import settings
from django.conf.urls import include
from django.contrib import admin
from django.urls import re_path
from django.views.static import serve

from .views import buscador, irc

from community.views import homepage

admin.autodiscover()

app_name = 'pyarweb'
urlpatterns = [
    re_path(r'^irc/$', irc, name='irc'),
    re_path(r'^buscador/$', buscador, name='buscador'),

    re_path(r'^$', homepage, name='homepage'),

    re_path(r'^noticias/', include('news.urls')),
    re_path(r'^empresas/', include(('pycompanies.urls', 'pycompanies'), namespace='companies')),
    re_path(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
    re_path(r'^summernote/', include('django_summernote.urls')),
    re_path(r'^trabajo-vieja/', include('jobs.urls')),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^accounts/', include('allauth.urls')),
    re_path(r'^eventos/', include(('events.urls', 'events'), namespace='events')),
    re_path(r'^captcha/', include('captcha.urls')),
    re_path(r'^trabajo/', include(('joboffers.urls', 'joboffers'), namespace='joboffers')),

    # no puedo usar el static porque no funcia en produccion y en prod django esta
    # sirviendo los archivos estaticos. Esto es sacado del codigo de la funcion.
    # si es un HACK, pero hasta que pueda solucionarlo usando django-assets o algo asi
    re_path(
        r'^%s(?P<path>.*)$' % re.escape(settings.STATIC_URL.lstrip('/')),
        serve,
        kwargs=dict(document_root=settings.STATIC_ROOT)
    ),
    re_path(
        r'^%s(?P<path>.*)$' % re.escape(settings.MEDIA_URL.lstrip('/')),
        serve,
        kwargs=dict(document_root=settings.MEDIA_ROOT)
    ),
]

joboffers/models.py
import html
import json
import re

from datetime import date
from urllib.parse import urlparse, urljoin

from autoslug import AutoSlugField
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.core.validators import MinLengthValidator
from django.db.models.aggregates import Count
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.utils.timezone import now
from django.utils.translation import gettext as _

from easyaudit.models import CRUDEvent
from taggit_autosuggest.managers import TaggableManager

from pycompanies.models import UserCompanyProfile
from .constants import STATE_LABEL_CLASSES


class EventType(models.IntegerChoices):
    """
    Types of event visualization
    """
    LISTING_VIEW = (0, _('Visualización en Listado'))
    DETAIL_VIEW = (1, _('Visualización de la oferta completa'))
    CONTACT_INFO_VIEW = (2, _('Apertura de la información de contacto'))


class Experience(models.TextChoices):
    """
    Choices for JobOffer Experience.
    """
    ZERO = '0', _('0')
    ONE_PLUS = '1+', _('1+')
    TWO_PLUS = '2+', _('2+')
    THREE_PLUS = '3+', _('3+')
    FIVE_PLUS = '5+', _('5+')
    TEN_PLUS = '10+', _('10+')


class Remoteness(models.TextChoices):
    """
    Choices for Remoteness.
    """
    REMOTE = 'REMOTE', _('Remoto')
    OFFICE = 'IN_OFFICE', _('Presencial')
    HYBRID = 'MIXED', _('Mixto')


class HiringType(models.TextChoices):
    """
    Choices for HiringType.
    """
    EMPLOYEE = 'EMPLOYEE', _('Relación de dependencia')
    MONOTRIBUTISTA = 'MONOTRIBUTO', _('Monotributista')
    CONTRACTOR_SHORT = 'CONTRACTOR_SHORT', _('Contractor short term')
    CONTRACTOR_LONG = 'CONTRACTOR_LONG', _('Contractor long term')
    COOPERATIVE = 'COOPERATIVE', _('Cooperativa de trabajo')
    GOVERNMENT = 'GOVERNMENT', _('Estado')
    OTHER = 'OTHER', _('Otra')


class OfferState(models.TextChoices):
    """
    Choices for JobOfferStates.
    """
    NEW = 'NEW', _('Nuevo')  # Used only for actions
    DEACTIVATED = 'DEACTIVATED', _('Desactivada')
    MODERATION = 'MODERATION', _('En moderación')
    ACTIVE = 'ACTIVE', _('Activa')
    REJECTED = 'REJECTED', _('Rechazada')
    EXPIRED = 'EXPIRED', _('Caducada')


class JobOffer(models.Model):
    """A PyAr Job Offer."""

    title = models.CharField(
      max_length=255, verbose_name=_('Título'), validators=[MinLengthValidator(20)]
    )
    company = models.ForeignKey(
        'pycompanies.Company',
        verbose_name=_('Empresa'),
        on_delete=models.CASCADE,
        null=True
    )
    location = models.CharField(max_length=100, blank=True, null=True, verbose_name=_('Lugar'))
    contact_mail = models.EmailField(
        max_length=255, blank=True, null=True, verbose_name=_('E-mail')
    )
    contact_phone = models.CharField(
        max_length=255, null=True, blank=True, verbose_name=_('Teléfono')
    )
    contact_url = models.CharField(
        max_length=255, null=True, blank=True, verbose_name=_('URL Contacto')
    )
    experience = models.CharField(
        max_length=3, choices=Experience.choices, verbose_name=_('Experiencia')
    )
    remoteness = models.CharField(
        max_length=32, choices=Remoteness.choices, verbose_name=_('Modalidad de trabajo')
    )
    tags = TaggableManager(verbose_name=_('Etiquetas'), blank=True)
    hiring_type = models.CharField(
        max_length=32, choices=HiringType.choices, verbose_name=_('Tipo de contratación')
    )
    salary = models.CharField(
        max_length=255, null=True, verbose_name=_('Rango salarial')
    )
    description = models.TextField(verbose_name=_('Descripción'))
    short_description = models.TextField(
        max_length=512,
        verbose_name=_('Descripción corta')
    )
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name=_('Hora de creación')
    )
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name=_('Creado por'),
        related_name='created_offers',
    )
    modified_at = models.DateTimeField(auto_now=True, verbose_name=_('Hora de Modificación'))
    modified_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name=_('Modificado por'),
        related_name='modified_offers',
    )
    state = models.CharField(
        max_length=32, choices=OfferState.choices, default=OfferState.DEACTIVATED,
        verbose_name=_('Estado de la oferta')
    )
    slug = AutoSlugField(populate_from='title', unique=True)

    def get_absolute_url(self):
        """
        Get the url of the joboffer without the domain, can be used in the site
        """
        return reverse('joboffers:view', kwargs={'slug': self.slug})

    def get_full_url(self):
        """
        Get the full url of the offer with domain and scheme prefix
        """
        prefix = urlparse(f"https://{settings.BASE_URL}").geturl()
        return urljoin(prefix, self.get_absolute_url())

    def __str__(self):
        return self.title

    @property
    def last_comment(self):
        """
        Return the last rejection JobOfferComment
        """
        return self.joboffercomment_set.last()

    @classmethod
    def get_short_description(cls, description):
        """
        Deduce the short_description from a given html description string
        """
        description_stripped_tags = re.sub(r'<[^>]*>', ' ', description)
        description_without_spaces = re.sub(r'\s+', ' ', description_stripped_tags).strip()
        description_unescaped = html.unescape(description_without_spaces)
        return description_unescaped[:512]

    def track_visualization(self, session, event_type: EventType):
        """
        Either get or create the matching JobOfferAccessLog instance for the joboffer.
        """
        today = date.today()
        month_year = today.year * 100 + today.month

        if session.session_key is None:
            session.save()

        return JobOfferAccessLog.objects.get_or_create(
            month_and_year=month_year,
            event_type=event_type,
            session=session.session_key,
            joboffer=self
        )

    def get_publisher_mail_addresses(self):
        """
        Return a list of the email addresses of the publishers of this offer.
        It filters users with empty mail field
        """
        profiles = UserCompanyProfile.objects.filter(company=self.company)

        addresses = set()
        for profile in profiles:
            if profile.user.email:
                addresses.add(profile.user.email)

        return addresses

    def get_visualizations_count(self):
        """
        Get a dict with visualizations count for every kind of event
        """
        items = JobOfferAccessLog.objects \
                                 .values_list('event_type') \
                                 .annotate(total=Count('event_type')) \
                                 .filter(joboffer=self) \
                                 .order_by()

        return dict(items)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        if not self.short_description:
            self.short_description = self.get_short_description(self.description)

        super().save(*args, **kwargs)

    @classmethod
    def get_options(cls):
        """
        Public _meta API accesor https://docs.djangoproject.com/en/4.0/ref/models/meta/
        """
        return cls._meta

    class Meta:
        constraints = [
            models.CheckConstraint(
                name='%(app_label)s_%(class)s_not_all_contact_info_null',
                check=(
                    models.Q(
                        contact_mail__isnull=False,
                    )
                    | models.Q(
                        contact_phone__isnull=False,
                    )
                    | models.Q(
                        contact_url__isnull=False,
                    )
                ),
            ),
            models.CheckConstraint(
                name='%(app_label)s_%(class)s_location_not_null_when_not_remote',
                check=(
                    (
                        models.Q(remoteness__in=(Remoteness.HYBRID, Remoteness.OFFICE))
                        & models.Q(location__isnull=False)
                    )
                    | models.Q(remoteness=Remoteness.REMOTE)
                ),
            ),
        ]


class CommentType(models.TextChoices):
    """
    Choices for Types of JobOfferComments.
    """
    MODERATION = 'MODERATION', _('Moderación')
    EDITION = 'EDITION', _('Edición')
    SPAM = 'SPAM', _('Spam')
    INSUFICIENT = 'INSUFICIENT', _('Información insuficiente')
    NOT_RELATED = 'NOT_PYTHON', _('Oferta no relacionada con Python')


class JobOfferComment(models.Model):
    """
    A comment on a JobOffer.
    """
    text = models.TextField(verbose_name=_('Texto'))
    comment_type = models.CharField(
        max_length=32, choices=CommentType.choices, verbose_name=_('Tipo'))
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name=_('Rango salarial')
    )
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name=_('Creado por'),
        related_name='created_joboffer_comments',
    )
    joboffer = models.ForeignKey(JobOffer, on_delete=models.CASCADE)

    @classmethod
    def get_options(cls):
        """
        Public _meta API accesor https://docs.djangoproject.com/en/4.0/ref/models/meta/
        """
        return cls._meta

    def __str__(self):
        return f"{self.joboffer.title}: {self.get_comment_type_display()}"


class JobOfferHistoryManager(models.Manager):
    def for_offer(self, joboffer):
        """
        Get all the history objects for a given joboffer. It can be JobOffer and JobOfferComment
        """

joboffers/templates/joboffers/_paginator.html
{% load i18n %}

<nav class="text-center" aria-label="Page navigation">
  <ul class="pagination pagination-lg">
    {% if page_obj.has_previous %}
    <li>
      <a href="?page={{ page_obj.previous_page_number }}" aria-label="{% trans 'Anterior' %}">
        <span aria-hidden="true">&larr;</span>
      </a>
    </li>
    {% endif %}
    {% for page_number in page_obj.paginator.page_range %}
    <li class="{% if page_number == page_obj.number %} active {% endif %}">
      <a href="?page={{ page_number }}">
        {{ page_number }}
      </a>
    </li>
    {% endfor %}

    {% if page_obj.has_next %}
    <li>
      <a href="?page={{ page_obj.next_page_number }}" aria-label="{% trans 'Siguiente' %}">
        <span aria-hidden="true">&rarr;</span>
      </a>
    </li>
    {% endif %}
  </ul>
</nav>

joboffers/templates/joboffers/_tags.html
{% load i18n %}
{% for tag in object.tags.all %}
      <span class="label label-primary" href="{% url 'joboffers:list' %}?tag_{{ tag.slug }}=1" >{{ tag.name }}</span>
{% endfor %}

joboffers/templates/joboffers/joboffer_admin.html
{% extends "base.html" %}
{% load devtags %}
{% load i18n static %}
{% block title %}Ofertas laborales con Python{% endblock %}

{% block content %}
<!-- Lista de trabajos -->
<main id="main" class="joboffers container" role="main" <section>
    <div class="page-header">
      <form id="search-form" class="input-group" role="form" action="{% url 'joboffers:admin' %}" method="get" novalidate>
        <input
          type="search" name="q" class="form-control input-lg"
          placeholder="{% trans 'Buscar ofertas...' %}" value="{{ q | default:'' }}" required>
        <span class="input-group-btn">
          <button class="btn btn-default btn-lg" type="submit">
            <span class="glyphicon glyphicon-search"></span>
          </button>
        </span>
      </form>

      <h2>{% trans 'Ofertas de trabajo de ' %} {{ company.name }}</h2>
    </div>

    {% if object_list %}
    <div class="list-group">
      {% for object in object_list %}
      <a href="{{ object.get_absolute_url }}" class="list-group-item">
        <h4 class="text-primary">
          {{ object.title }}<span class="job-date">({{ object.modified_at|date:"SHORT_DATE_FORMAT" }}, {{ object.location }})</span>
        </h4>
        <p>{{ object.short_description }}</p>
        <div class="text-right">
          {% include "joboffers/_tags.html" %}
        </div>
      </a>
      {% endfor %}
    </div>

        {% include 'joboffers/_paginator.html' with page_obj=page_obj %}

    </div>
    {% else %}
    <div class="col-md-12">
        <p>{% trans 'No se encontraron ofertas.' %}</p>
    </div>
    {% endif %}

    <hr />

    <div class="section-button-group pull-right">
        <a href="{% url 'joboffers:add' %}" class="btn btn-info">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            {% trans 'Nueva Oferta' %}
        </a>
    </div>
    </section>

</main>
{% endblock %}

joboffers/templates/joboffers/joboffer_analytics.html
{% extends "base.html" %}
{% load i18n %}
{% load email_obfuscator %}
{% load devtags %}

{% block title %}
{{ object.title }}
{% endblock %}

{% block content %}
<main id="main" class="joboffers container" role="main">
  <div class="col-lg-12">
    <div class="page-header">
      <h2>{% trans 'Estadísticas de ' %} {{ object.title }}</h2>
    </div>

    <div class="row">
      <div class="col-xs-12">
        <h2>{% trans 'Resumen de Visualizaciones' %}
          <a href="{% url 'joboffers:download-analytics-csv' object.slug %}" class="btn btn-primary pull-right"
            title="{% trans 'Descargar una planilla con el detalle de todas las visitas' %}">
            <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
            {% trans 'Descargar como archivo .csv' %}
          </a>
        </h2>

          <table class="table table-bordered" style="max-width: 400px; margin: auto;">
            {% for concept_name, total in totals %}
            <tr>
              <td>{{ concept_name }}</td>
              <th>{{ total }}</th>
            </tr>
            {% endfor %}
          </table>

        {% for title, graph in graphs %}
          {% if graph %}
            <h2>{{ title }}</h2>
              {% autoescape off %}
                {{ graph }}
              {% endautoescape %}
          {% endif %}
        {% endfor %}
      </div>
    </div>
  </div>
</main>
{% endblock %}

joboffers/templates/joboffers/joboffer_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load email_obfuscator %}
{% load devtags %}

{% block title %}
{{ object.title }}
{% endblock %}

{% block extra_head %}
  <meta property="og:title" content="{{ object.title }}">
  <meta name="description" property="og:description" content="{{ object.short_description }}">
  {% if object.company.photo %}
  <meta property="og:image" content="{{ object.company.photo.url }}">
  {% endif %}
{% endblock %}

{% block content %}
<main id="main" class="joboffers container" role="main">
  <div class="col-lg-12">
    <div class="page-header">
      <h2>{{ object.title }}</h2>
    </div>

    <div class="row">
      <div class="col-md-8">
        {% if object.state == OfferState.REJECTED %}
          <div class="alert alert-danger" role="alert">
            <h4>La oferta fue rechazada por el equipo de moderación</h4>
            <hr />
            <p>
              {% translate 'El motivo fué' %} <strong>{{ object.last_comment.get_comment_type_display | lower }}</strong>
              {% translate 'y la observación fué:' %} <strong>{{ object.last_comment.text }}</strong>.
            </p>
            <p>
              {% translate 'Verifique si es posible corregirla para que se adapte a los requerimientos.' %}
            </p>
          </div>
        {% endif %}
        <div>
          {{ object.description|safe }}
        </div>
        <div class="text-right">
          {% include "joboffers/_tags.html" %}
        </div>
      </div>

      <div class="col-md-4">
        <div class="offer-detail panel panel-default panel-primary">
          <div class="panel-heading"><strong>Datos de la oferta laboral</strong></div>
          <div class="panel-body">
            {% include 'joboffers/joboffer_overview.html' with obj=object label_class=state_label_class %}
          </div>
        </div>
      </div>
    </div>
    <div class="pull-right">
      {% for button in action_buttons %}
      <a href="{% url button.target_url object.slug %}" class="btn {{ button.css_classes|join:' ' }}"
        title="{% if button.title %}{{ button.title }}{% else %}{{ button.text }}{% endif %}">
        {{ button.text }}
        <span class="glyphicon {{ button.icon_class }}" aria-hidden="true"></span>
      </a>
      {% endfor %}
    </div>
  </div>
</main>
{% endblock %}

joboffers/templates/joboffers/joboffer_form.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% load devtags %}

{% block extra_head %}
<script type="text/javascript">
// Taken from jquery.init.js from django/admin
/* El plguin que sugiere tags (django-taggit-autosuggest) está pensado para funcionar
en el admin de django, entonces espera que django.jQuery esté definido.
*/
var django = {
    "jQuery": jQuery.noConflict(true)
};
var jQuery = django.jQuery;
var $=jQuery;
</script>
{% endblock %}

{% block content %}
<main id="main" class="joboffer container" role="main">
    <div class="col-lg-12">
	    <div class="page-header">
	    	<h2>{% if form.instance.id %}
	    			{% trans 'Actualizando información' %}
	    		{% else %}
	    			{% trans 'Agregar un nuevo empleo' %}
	    		{% endif %}
	    	</h2>
	    </div>
	    <script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
	    {% crispy form %}
	</div>
</main>
{% endblock %}

joboffers/templates/joboffers/joboffer_history.html
{% extends "base.html" %}
{% load i18n %}
{% load devtags %}
{% load history %}

{% block title %}
{{ object.title }}
{% endblock %}

{% block content %}
<main id="main" class="container" role="main">

    <div class="col-lg-12">

      <div class="page-header">
        <h2>Historial de «{{ object.title }}» </h2>
      </div>

        <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
          {% for history_entry in object_list %}
          <div class="panel panel-default">
            {% include 'joboffers/history/_header.html' %}
            <div id="change-{{ forloop.counter }}" class="panel-collapse collapse" role="tabpanel">
              <div class="panel-body">
                {% if history_entry.content_type.model == "joboffer" %}
                  {% if history_entry.event_type == JobOfferHistory.CREATE %}
                    {% include 'joboffers/history/_create.html' %}
                  {% else %}
                    {% include 'joboffers/history/_update.html' %}
                  {% endif %}

                {% else %}
                  {% include 'joboffers/history/_comment.html' with comment=history_entry.joboffer_comment %}
                {% endif %}
              </div>
            </div>
          </div>
          {% empty %}
            <p>No hay registros históricos para esta oferta.</p>
          {% endfor %}
        </div>
        {% include 'joboffers/_paginator.html' with page_obj=page_obj %}
    </div>
</main>
{% endblock %}

joboffers/templates/joboffers/joboffer_list.html
{% extends "base_site.html" %}
{% load devtags i18n static %}
{% block title %}Ofertas laborales con Python{% endblock %}

{% block left-column %}

<!-- Job Offers List -->
<section>
    <div class="col-md-12">
        <div class="page-header">
            <h2>{% trans 'Ofertas laborales con Python' %}
                <span class="section-button-group pull-right">
                    <a href="{% url 'joboffers:add' %}" class="btn btn-info">{% trans 'Publicar oferta laboral' %}</a>
                </span>
            </h2>
        </div>
        {% if object_list %}
            {% for object in page_obj %}
                <div class="{% if object.company.rank != 0 %} sponsored-jobs bg-info {% endif %} mp-10">
                    <h4>
                        <a href="{{ object.get_absolute_url }}">{{ object.title }}</a>  <span class="job-date">{{ object.modified_at|date:"SHORT_DATE_FORMAT" }}, {{ object.location }}</span>
                    </h4>
                    <p>{{ object.short_description}}</p>
                    <div class="text-muted">
                    {% include "joboffers/_tags.html" %}
                      <p><a href="{{ object.get_absolute_url }}">{% trans 'Leer más...' %}</a></p>
                    </div>
                </div>
            {% endfor %}

            {% include 'joboffers/_paginator.html' with page_obj=page_obj %}

        {% else %}
            <div class="col-md-12">
                <p>{% trans 'La búsqueda no produjo resultados.' %}</p>
            </div>
        {% endif %}
        <div class="pull-right">
            <a href="{% url 'joboffers:feed' %}" class="badge">
                <i class="fa fa-rss"></i> RSS
            </a>
        </div>
    </div>
</section>
{% endblock %}

{% block right-column %}
  {% if user.is_authenticated %}
    {% include "companies/_user_actions.html" %}
  {% endif %}

  {% include "_tags_filtering_form.html" %}
{% endblock %}

joboffers/templates/joboffers/joboffer_overview.html
{% load i18n static %}
<dl>
  <dt>Estado</dt>
  <dd>
    <h4 class="mt-0">
      <label class="label {{label_class}}">
        {{ obj.get_state_display }}
      </label>
    </h4>
  </dd>
  <dt>Última Modificación</dt>
  <dd>
    {{ obj.modified_at|date:"SHORT_DATETIME_FORMAT" }}
  </dd>
  {% if obj.location %}
  <dt>Lugar de trabajo</dt>
  <dd>{{ obj.location|title }}</dd>
  {% endif %}

  {% if obj.company %}
    <dt>Empresa</dt>
    <dd>
      <a href="{{ obj.company.get_absolute_url }}">{{ obj.company.name }}</a>
    </dd>
  {% endif %}
  <dt>Permite trabajar remoto</dt>
  <dd>{% if obj.remote_work %}Si{% else %}No{% endif %}</dd>

  <dt>Experiencia Requerida</dt>
  <dd>{{ obj.get_experience_display }}</dd>

  <dt>Modalidad de Trabajo</dt>
  <dd>{{ obj.get_remoteness_display }}</dd>

  <dt>Tipo de Contratación</dt>
  <dd>{{ obj.get_hiring_type_display }}</dd>

  <dt>Rango Salarial</dt>
  <dd>{{ obj.salary }}</dd>

  <!-- Agregar informacion de contacto que se despliegue con un botón y que no se muestre si esta inactiva la oferta -->

</dl>

<a class="btn btn-info w-100" onclick="trackContactInfo()" role="button" data-toggle="collapse" href="#contact-info" aria-expanded="false" aria-controls="collapse">
  {% translate 'Ver Información de Contacto' %}
</a>
<div class="collapse" id="contact-info">
  <ul class="list-unstyled contact-info">
    {% if obj.contact_mail %}
    <li>
      <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
      {{ obj.contact_mail }}
    </li>
    {% endif %}
    {% if obj.contact_url %}
    <li>
      <span class="glyphicon glyphicon-link" aria-hidden="true"></span>
      {{ object.contact_url }}
    </li>
    {% endif %}
    {% if obj.contact_phone %}
    <li>
      <span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>
      {{ object.contact_phone }}
    </li>
    {% endif %}
  </ul>

</div>
<script src="{% static 'js/joboffer_track.js' %}"></script>

joboffers/templates/joboffers/joboffer_reject.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block content %}
<main id="main" class="joboffer container" role="main">
  <div class="col-lg-12">
	  <div class="page-header">
	    <h2>{% trans 'Motivo de Rechazo' %}
	    </h2>
	  </div>
	  {% crispy form %}
	</div>
</main>
{% endblock %}